Feat/main page
ShaggyBa/team-project-todo-app pull request #2
Opened 2023-09-12 22:28 UTC by UniverseArc

Заготовки главной страницы. Пока только совсем-совсем скелет. Много ушло времени на дебаг **### _дол6А3ба_** гита, и прокруткой маховика с точки зрения применения моих знаний для написания прода с нуля.

Позже (с утра) 
Займусь подключением редакса, прокидкой пропсов, плейсхолдеров, аватарок, стилизацией. В общем - прической до требуемого от таски вида.

2023-09-12 22:38 UTC, ShaggyBa commented on src/App.module.css
> +.todoApp_Wrapper {
todoApp__wrapper

2023-09-12 22:39 UTC, ShaggyBa commented on src/App.module.css
> -.todoApp_MainWrapper{
todoApp__wrapper-main

2023-09-12 22:52 UTC, ShaggyBa commented on src/index.css
> +	font-family: 'Lato'
font-family: 'Lato', sans-serif:

2023-09-12 23:05 UTC, ShaggyBa reviewed
Пойдет, есть одно замечание по поводу наименования классов.
Если придерживаться методологии БЭМ (а мы должны ее придерживаться):
1. Нужно делать два нижних подчеркивания у дочерних элементов, которые являются частью данной группы элементов (блока). 
<div className="todoApp">
<div className="todoApp__wrapper"></div>
</div>
2. Класс .todoApp_MainWrapper должен записываться как
.todoApp__wrapper--main (где ...__wrapper -> дочерний элемент блока, а ...--main -> его модификатор) Хотя два wrapper-а не может быть на странице, wrapper синтаксически - одна оболочка над всей страницей, которая обычно юзается для растягивания всего контента, ты сделал правильно, что обернул wrapper-ом всю компоненту, но вместо использования todoApp_MainWrapper лучше юзай так:

<main className="cssStyles.main">
<div className="cssStyles.container">...</div>
</main>
P.S (container - это такая же оболочка как wrapper, а не блок, поэтому не нужно задавать вложенным элементам префикс __  -> container__title и тд.)

Docs: https://ru.bem.info/methodology/quick-start/

Подправь названия классов стилистически верно, исправленные версии закинь на элементы.

2023-09-13 07:49 UTC, mr-mollusk requested changes
В целом неплохо, все недочёты из-за неопытности, для первого пул реквеста - вполне себе

2023-09-13 07:49 UTC, mr-mollusk commented on src/App.tsx
> +import Header from "./components/Header/Header";
Поправь импорты как я показывал. Если ты экспортируешь компоненту из файла, а после из папки components, то у тебя все импорты компоненты будут в одной строчке из `"./components"`

2023-09-13 07:49 UTC, mr-mollusk commented on src/App.tsx
> +			<header className={cssStyles.todoApp_Header}>
Ненене. Смотри. У тебя уже есть компонента `<Header>`. Так зачем ты оборачиваешь её в нативный `<header>`, если можно сделать так, чтобы компонента возвращала тебе хэдэр. Вижу в файлах ниже - там напишу.
Страницы лучше делать максимально тонкими. Что-то вроде:
``` TSX

const App: React.FC = () => {
  return (
    <>
      <Header />
      <Main />
      <Footer />
    </>
  );
};
```

2023-09-13 07:49 UTC, mr-mollusk commented on src/App.tsx
> +				<div className={cssStyles.todoApp_NavArea}>
Ну тут с каждым компонентом так. Их бы отрефакторить

2023-09-13 07:49 UTC, mr-mollusk commented on src/UI-colors.css
> +    --darkToBrighterOneGray: #5C5C5C;
Слишком длинное название и непонятное. Лучше найди в палитре и задавай оттенками. Например gray-200. Понятнее будет. Вот пример https://chakra-ui.com/docs/styled-system/theme#gray

2023-09-13 07:49 UTC, mr-mollusk commented on src/UI-colors.css
> +    --anotherWhite: #F1F1F1;
Аналогично. Другой белый - звучит странно

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/Footer/Footer.tsx
> +		<div className={cssStyles.Footer}>
Зачем возвращать `<div>` если можно `<footer>`

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/Header/Header.module.css
Пустой файл - не есть классно

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/Header/Header.tsx
> +		<div className={cssStyles.Header}>
Возвращай `<header>`

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/MainContent/MainContent.tsx
> +		<div className={cssStyles.MainContent}>
Можно возвращать `<main>`

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/Sidebar/Sidebar.tsx
> +		<div className='sidebar'>
Можно вернуть тэг `<aside>`. Семантическая вёрстка - мать её)

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.module.css
> +	color: #767676;
Цвета в переменные

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.module.css
> +	width: 10px;
Не обязательно фиксить, но короче мы такие штуки обычно делаем так:
``` css
.variantBtn img {
    --size: 10px;
    margin-right: 10px;
    width: var(--size);
    height: var(--size);
}
```
Оно как бы не сильно полезно, просто если надо поменять - тебе менять всегда одно значение. Иногда быстрее и полезнее, особенно если у тебя какие-то медиа запросы и ты в них не хардкодишь значения, а рассчитываешь относительно какой-то переменной. Всё само подстроится

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.module.css
> +	box-shadow: 1px 1px 10px 1px #767676;
Тени тоже лучше выносить в переменные, причём внутри этой переменной цвет лучше доставать из переменной. Создаём удобную матрёшку. Намного приятнее писать названия цветов, чем непонятные циферки, которые мы конечно копируем из фигмы, но потом страдаем, когда эти циферки в фигме меняются

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.tsx
> +export const VariantBtn: React.FC<IButton> = ({ variant }): JSX.Element => {
Избыточная типизация. `React.FC` подразумевает, что ты вернёшь JSX разметку - тебе не обязательно писать возвращаемый тип

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.tsx
> +	switch (variant) {
Кнопка не удобная. Ты по сути сделал не Dumb Component. Я понимаю, что тут смысл в том, что ты задал тип кнопки и она сама подставилась быстренько, а теперь задумайся, если количество кнопок вырастет до 10. 100. 1000. ?
Во-первых добавь типизацию
``` TSX
React.PropsWithChildren<React.FC<IButton>>
```
Эта штука позволит тебе прокинуть проп children
Туда будет попадать всё, что ты оборачиваешь вот так:
``` TSX
<button>Вот этот текст попадёт в children</button>
```
И теперь просто вместо махинаций с button text просто делаешь
``` TSX
<span>{children}<span>
```

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.tsx
> +	switch (variant) {
Теперь по поводу иконок. Очень неудобно их хардкодить. Тут есть 2 варианта. Либо передавай их в children либо передавай их в пропсы. Первый способ - просто засовываешь иконку внутрь тэга. Второй:
Создаёшь в IButton новое поле:
``` TSX
export interface IButton {
    iconLeft?: ReactNode;
}
```
Пробрасываешь это в пропсы и просто в кнопке делаешь так:
``` TSX
<button>{iconLeft && iconLeft}{children}</button>
```
Теперь при желании ты можешь добавить такую же иконку справа и вуаля, ты можешь в свою кнопку прокидывать 1 или даже 2 иконки

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/VariantBtn/VariantBtn.tsx
> +		<button className={`${s.variantBtn}`}>
```TSX
<button className={s.variantBtn}>
```

2023-09-13 07:49 UTC, mr-mollusk commented on src/types/IButton.types.ts
> +export type TVariantsOfButton = "add-list" | "add-task" | "delete-list" | "delete-task";
По хорошему исходя из дизайна - тебе нудны другие типы. `"Primary"` и `"Secondary"`. Первое - та зелёная кнопка, вторая - серая (кнопка "отмена"). Навешиваешь в зависимости от этого пропса класс и красишь кнопочку. И каеф

2023-09-13 07:49 UTC, mr-mollusk commented on src/types/ISidebar.types.ts
> +	lists: []
Массив чего?

2023-09-13 07:49 UTC, mr-mollusk commented on src/components/Sidebar/Sidebar.module.css
Пустой файл - не комильфо

2023-09-13 07:58 UTC, mr-mollusk commented
И обрати внимание, что у тебя реквест на merge в master, а не dev. Ты уверен?

2023-09-13 13:17 UTC, UniverseArc commented
> Пойдет, есть одно замечание по поводу наименования классов. Если придерживаться методологии БЭМ (а мы должны ее придерживаться):
> 
> 1. Нужно делать два нижних подчеркивания у дочерних элементов, которые являются частью данной группы элементов (блока).
> 
> 2. Класс .todoApp_MainWrapper должен записываться как .todoApp__wrapper--main (где ...__wrapper -> дочерний элемент блока, а ...--main -> его модификатор) Хотя два wrapper-а не может быть на странице, wrapper синтаксически - одна оболочка над всей страницей, которая обычно юзается для растягивания всего контента, ты сделал правильно, что обернул wrapper-ом всю компоненту, но вместо использования todoApp_MainWrapper лучше юзай так:
> ...
> P.S (container - это такая же оболочка как wrapper, а не блок, поэтому не нужно задавать вложенным элементам префикс __ -> container__title и тд.)
> Docs: https://ru.bem.info/methodology/quick-start/
> 
> Подправь названия классов стилистически верно, исправленные версии закинь на элементы.
Положим ситуацию: У меня идёт обёртка, у которой класс todoApp__header. Внутри вызывается компонента <Header />. В компоненте <Header /> класс всё равно должен быть todoApp__header-(любое осмысленное название), учитывая что файл, в котором находится "обертка" - у меня один ксс. А компонента подчинена другому ксс. Либо же я могу внутри компоненты пользоваться названиями классов свободно?
![image](https://github.com/ShaggyBa/team-project-todo-app/assets/93486544/e287b825-fa6a-40ff-b5d8-47e0a55dda66)
![image](https://github.com/ShaggyBa/team-project-todo-app/assets/93486544/3ab15a75-c2c2-4c1a-b3ea-58a78a90f785)

2023-09-13 13:36 UTC, UniverseArc commented on src/App.tsx
> +import Header from "./components/Header/Header";
Насчет импортов совсем не понял.
У меня в соц. сети димыча миллион импортов компонент, и это как бы нормально было....
У меня сначала идет папка components потом в ней папка для компоненты и уже в ней сам файл с компонентой + module css, итого:
components/Header/Header
![image](https://github.com/ShaggyBa/team-project-todo-app/assets/93486544/5f2ff56d-d6f1-4865-8947-d4a745dd080b)

И как это делать тоже не особо нашел. Там везде в импортах фигурирует _**один файл**_ всего, откуда импортируют.
Не говорю уже о папках, и множестве файлах внутри

2023-09-13 13:49 UTC, UniverseArc commented on src/App.tsx
> +			<header className={cssStyles.todoApp_Header}>
Оставил коммент в App.tsx, можешь глянуть

2023-09-13 13:49 UTC, UniverseArc commented on src/UI-colors.css
> +    --darkToBrighterOneGray: #5C5C5C;
В dev, в feat/colors уже релизнулось :>

2023-09-13 13:50 UTC, UniverseArc commented on src/components/Header/Header.module.css
Ну он там как заготовка остался))

`RETURN 0 xdxdxdxdxdxd`

2023-09-13 13:50 UTC, UniverseArc commented on src/components/MainContent/MainContent.tsx
> +		<div className={cssStyles.MainContent}>
а вот это не знав..

2023-09-13 13:52 UTC, UniverseArc commented on src/components/VariantBtn/VariantBtn.module.css
> +	color: #767676;
а ета уже не маё!!

2023-09-13 13:52 UTC, UniverseArc commented on src/components/VariantBtn/VariantBtn.module.css
> +	color: #767676;
Но сделаю)))))))))))))

2023-09-13 13:53 UTC, UniverseArc commented on src/components/VariantBtn/VariantBtn.module.css
> +	width: 10px;
`vse ravno sdelau....`

2023-09-13 13:54 UTC, UniverseArc commented on src/components/VariantBtn/VariantBtn.tsx
> +export const VariantBtn: React.FC<IButton> = ({ variant }): JSX.Element => {
![image](https://github.com/ShaggyBa/team-project-todo-app/assets/93486544/924877be-d55a-405b-9fbe-3e2e013748c8)

2023-09-13 13:55 UTC, UniverseArc commented on src/components/VariantBtn/VariantBtn.tsx
> +	switch (variant) {
💀

2023-09-13 13:56 UTC, UniverseArc commented on src/components/Sidebar/Sidebar.module.css
В некст коммите ни пустой!!

2023-09-13 16:22 UTC, mr-mollusk commented on src/App.tsx
> +import Header from "./components/Header/Header";
Хорошо про импорты отдельно на созвоне объясню

2023-09-13 17:06 UTC, mr-mollusk approved these changes
Пока сойдёт, остальные правки косметические, я по ходу их обнаружу

2023-09-13 17:31 UTC, merged